export const siteConfig = {
  name: "Tikat",
  legalName: "Tikat - Studio Thiết Kế & Phát Triển Website, Web App Chuyên Nghiệp",
  shortDescription: "Tikat - Studio Lập Trình & Thiết Kế Website, Web App, SaaS Đẳng Cấp",
  description:
    "Tikat (tikat.com) - Studio chuyên thiết kế & lập trình website cao cấp, web application, SaaS, portal doanh nghiệp chuẩn SEO và tối ưu Core Web Vitals <0.8s bởi Nguyễn Lê Đình Tiên. Bàn giao 100% full source code, bảo hành 12 tháng, phục vụ khách hàng tại Đà Nẵng, Hà Nội, TP. Hồ Chí Minh, toàn quốc & quốc tế.",
  url: "https://tikat.com",
  ogImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
  founderAvatar: "https://res.cloudinary.com/daqwg8oql/image/upload/v1788340491/avatars/jz0d8qdz46wtga0eh6uk.jpg",
  keywords: [
    "Tikat",
    "tikat.com",
    "Nguyễn Lê Đình Tiên",
    "tiennguyen2507",
    "thiết kế website Đà Nẵng",
    "freelance đà nẵng",
    "làm web đà nẵng",
    "nhận làm web app đà nẵng",
    "Front-end Developer Đà Nẵng",
    "Full-stack Developer Đà Nẵng",
    "thiết kế website Hà Nội",
    "thiết kế website Hồ Chí Minh",
    "thiết kế website chuẩn SEO",
    "lập trình web app chuyên nghiệp",
    "phát triển phần mềm SaaS",
    "lập trình Next.js React",
    "tối ưu tốc độ website pagespeed",
    "thiết kế website bán hàng cao cấp",
    "portal quản lý doanh nghiệp ERP CRM",
    "bàn giao full source code Git",
    "web development studio Vietnam"
  ],
  author: "Nguyễn Lê Đình Tiên",
  authorRole: "Front-end Developer & Freelance Web Specialist",
  geo: {
    // Primary Hub - Da Nang HQ
    region: "VN-DN",
    placename: "Đà Nẵng",
    position: "16.054407;108.202167",
    icbm: "16.054407, 108.202167",
    country: "VN",
    countryName: "Việt Nam",
    city: "Đà Nẵng",
    postalCode: "550000",
    latitude: 16.054407,
    longitude: 108.202167,

    // Regional Branch - TP. Ho Chi Minh
    hcmRegion: "VN-SG",
    hcmPlacename: "Hồ Chí Minh",
    hcmPosition: "10.776889;106.700806",
    hcmLatitude: 10.776889,
    hcmLongitude: 106.700806,
    hcmPostalCode: "700000",

    // Regional Branch - Ha Noi
    hnRegion: "VN-HN",
    hnPlacename: "Hà Nội",
    hnPosition: "21.028511;105.854167",
    hnLatitude: 21.028511,
    hnLongitude: 105.854167,
    hnPostalCode: "100000",
  },
  contact: {
    phone: "0886694350",
    hotlineDisplay: "088 669 4350",
    email: "Nguyenledinhtien2507@gmail.com",
    contactEmail: "contact@tikat.com",
    address: "Đà Nẵng, Việt Nam",
    danangOffice: "Hải Châu, Đà Nẵng",
    addressHcm: "Bitexco Financial Tower, Quận 1, TP. Hồ Chí Minh",
    addressHn: "Keangnam Landmark 72, Cầu Giấy, Hà Nội",
    openingHours: "Mo-Sa 08:00-22:00",
    latitude: 16.054407,
    longitude: 108.202167,
    bank: {
      bankName: "TPBank",
      accountNumber: "25079962507",
      accountHolder: "NGUYEN LE DINH TIEN",
    },
  },
  socials: {
    facebook: "https://www.facebook.com/tiennguyen2507",
    github: "https://github.com/tiennguyen2507",
    zalo: "https://zalo.me/0886694350",
    portfolio: "https://nguyenledinhtien.io.vn",
    portfolioInfo: "https://nguyenledinhtien.io.vn/info",
    shopeeLinkEarn: "https://shopeelinkearn.io.vn",
    telegram: "https://t.me/tikat_support",
    linkedin: "https://linkedin.com/company/tikat",
  },
  skills: [
    "Next.js",
    "React",
    "TypeScript",
    "Node.js",
    "PostgreSQL",
    "Supabase",
    "Tailwind CSS",
    "SaaS Architecture",
    "SEO & Core Web Vitals Optimization",
    "E-Commerce & Payment Integration",
    "REST & GraphQL APIs"
  ],
  themeColor: "#FFFFFF",
};
