export const siteConfig = {
  name: "Dom Solution",
  legalName: "Dom Solution - Web & Web App Development",
  shortDescription: "Freelance Full-stack Web & Web App Development",
  description:
    "Dom Solution - Chuyên thiết kế và lập trình website, web application, SaaS, portal quản lý doanh nghiệp chất lượng cao, chuẩn SEO, tối ưu tốc độ & bảo mật. Bàn giao 100% full source code, bảo hành 12 tháng.",
  url: "https://domsolution.dev",
  ogImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
  keywords: [
    "Dom Solution",
    "thiết kế website",
    "lập trình web app",
    "phát triển SaaS",
    "freelance web developer",
    "lập trình Next.js",
    "lập trình React TypeScript",
    "website doanh nghiệp chuẩn SEO",
    "thiết kế web bán hàng",
    "portal quản lý doanh nghiệp",
    "tích hợp thanh toán vnpay momo",
    "tối ưu tốc độ website pagespeed"
  ],
  author: "Dom Solution Engineering Team",
  contact: {
    phone: "0968889999",
    hotlineDisplay: "0968 889 999",
    email: "contact@domsolution.dev",
    address: "Hà Nội & TP. Hồ Chí Minh (Nhận dự án Remote toàn quốc & quốc tế)",
    hanoiOffice: "Cầu Giấy, Hà Nội",
    hcmOffice: "Quận 1, TP. Hồ Chí Minh",
    openingHours: "Mo-Sa 08:30-21:30",
    latitude: 21.0285,
    longitude: 105.8542,
  },
  socials: {
    facebook: "https://facebook.com/domsolution.dev",
    github: "https://github.com/domsolution",
    telegram: "https://t.me/domsolution",
    zalo: "https://zalo.me/0968889999",
    linkedin: "https://linkedin.com/company/domsolution",
  },
  themeColor: "#0D5BE1",
};
